# Server settings
server:
  port: 8081
  tomcat:
    max-threads: 100

spring:
  datasource:
    hikari:
      maximum-pool-size: 20
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    locations: classpath:db/h2/migration

simplelib:
  default:
    onPage: 5

logging:
  level:
    org.springframework.data: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG